# Generated by Django 4.1.7 on 2023-02-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_myuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
